spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc8th?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-id: 0677733cd5593f1daf468e85ef69b253
            client-secret: AxMoGrJK3BGJrQYUezHqWC3WIfeaOOSK
            redirect-uri: http://43.200.177.104:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao

jwt:
  token:
    secretKey: umceightfightingjwttokenauthentication
    expiration:
      access: 14400000